services:
  bot:
    image: neimes/vpn_bot:latest
    container_name: vpn_bot
    restart: no
    env_file:
      - .env
    volumes:
      - ./:/db
    networks:
      - external
    environment:
      - PYTHONPATH=/app
  
networks:
  external:
    driver: bridge
